### ISSUE TITLE
[FEATURE] - Support Schema on write

### ISSUE THREAD

**Issue by hayssams** [starlake-ai/starlake#50]
## Description
Many Database including Snowflake and other relational databases require the table schema to be created upfront.
Even when addressing BigQuery, some users would like the schema to be created upfront too even though it is not required.

This feature would add a new command that would create the required DDL. We call this command infer-ddl.
Databases usually evolve in time. This command should also address the issue of altering the table schema if it already exist in the database.

// Use mapping specifict BigQuery and generate create/alter table statements
starlake.sh infer-ddl --datawarehouse bigquery --connection bq 

// Use mapping default mapping and generate create/alter table statements
starlake.sh infer-ddl --connection bq
starlake.sh infer-ddl --datawarehouse sql --connection bq --output ./sql

// use default mapping and generate and apply create/alter table statements
starlake.sh infer-ddl --datawarehouse sql --connection bq --apply

// use default mapping and generate and apply create/alter table statements using the provided moustache template
starlake.sh infer-ddl --datawarehouse sql --template my template.mustache --connection bq --apply

## Solution proposition
We augment the types.yml file to include a mapping section with case specific to each data warehouse when necessary :
```
type:
  name: int
  pimitiveType: long
  mapping:
    bigquery: LONG # Specific to BigQuery
    synapse: INTEGER # Specific to Synapse
    sql: NUMERIC # used by default when no specific defined for the target data warehouse
```

From the schema we generate the final DDL statements and apply them gif requested using the provided connection

## Complexity estimation
T-Shirt Size: M
